ProjectName:
  - WanAndroid
  -

# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
TesterName: 菜头

# 域名1
host: https://www.wanandroid.com
# 域名2, 支持多个域名配置
app_host: https://www.wanandroid.com

# 报告通知类型：0：不发送通知 1：钉钉 2：企业微信通知 3：邮箱通知 4：飞书通知
NotificationType: 3

# 数据库相关配置
MySqlDB:
  # 数据库开关
  switch: False
  host: 'localhost'
  user: 'root'
  password: '123456'
  db: 'testdb2'

# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

email:
  send_user: allan0706@sina.cn
  email_host: smtp.sina.cn
  stamp_key: 2c3921efe562cd83
  #收件人
  send_list: 917042025@qq.com

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: False